import fs from "node:fs";
import express from "express";
import path from "node:path";
import { z } from "zod";
import { AnalysisService } from "../core/service.js";
import { CreatorResearchService } from "../core/creator-research-service.js";
import { ComparisonProjectService } from "../modules/comparison/service.js";
import { projectRoot, runtimeDir } from "../core/config.js";
import { createCreatorResearchRunInputSchema, createRunInputSchema } from "../shared/schema.js";
import { loadCreatorSummaries } from "./creators.js";
import { loadCreatorDossier } from "./creator-dossier.js";
import { buildCreatorDepthParityManifest } from "./creator-depth-parity.js";
import { loadVideoResearch } from "./video-research.js";
import { loadComparisonDossier } from "./comparison-dossier.js";
import { createDurableResearchLearningService } from "./research-learning.js";
import {
  addLearningLoopArtifactInputSchema,
  addLearningLoopCasesInputSchema,
  adjudicateLearningLoopInputSchema,
  beginLearningLoopRegressionInputSchema,
  beginLearningLoopBlindInputSchema,
  createDurableLearningLoopControlPlane,
  createLearningLoopInputSchema,
  moveLearningLoopInputSchema,
  recordLearningLoopDiagnosisInputSchema,
  recordLearningLoopLensGateInputSchema,
  recordLearningLoopRegressionInputSchema,
  recordLearningLoopBlindResultInputSchema,
  stopLearningLoopInputSchema,
  type LearningLoopControlPlane
} from "./learning-loop.js";

function learningLoopError(response: express.Response, error: unknown): express.Response {
  const message = error instanceof z.ZodError
    ? error.issues[0]?.message ?? "输入无效"
    : error instanceof Error ? error.message : "学习循环操作失败";
  const status = message.includes("not found") || message.includes("不存在")
    ? 404
    : message.includes("cannot") || message.includes("required") || message.includes("missing") ? 409 : 400;
  return response.status(status).json({ error: message });
}

export function createApp(
  service = new AnalysisService(),
  creatorResearchService = new CreatorResearchService(),
  comparisonProjectService = new ComparisonProjectService(creatorResearchService),
  researchLearningService = createDurableResearchLearningService(),
  learningLoopControlPlane: LearningLoopControlPlane = createDurableLearningLoopControlPlane()
) {
  const app = express();
  const clientDirectory = path.join(projectRoot, "dist");
  app.use(express.json({ limit: "1mb" }));
  app.use("/artifacts", express.static(path.join(runtimeDir(), "runs"), {
    fallthrough: false,
    immutable: true,
    maxAge: "1h"
  }));

  app.use("/research", express.static(path.join(projectRoot, "artifacts", "creator-research"), {
    setHeaders: (response, filePath) => {
      // JSON data files are regenerated by analysis scripts; never serve stale copies.
      if (filePath.endsWith(".json")) response.setHeader("Cache-Control", "no-cache");
    }
  }));

  app.get("/api/health", (_request, response) => {
    response.json({ ok: true });
  });

  app.get("/api/creators", (_request, response) => {
    response.json({ creators: loadCreatorSummaries() });
  });

  app.get("/api/creator-runs", (request, response) => {
    const limit = Math.min(100, Math.max(1, Number(request.query.limit ?? 50)));
    response.json({ runs: creatorResearchService.list(limit) });
  });

  app.get("/api/creator-runs/:id", (request, response) => {
    const run = creatorResearchService.get(request.params.id);
    if (!run) return response.status(404).json({ error: "博主分析任务不存在" });
    return response.json(run);
  });

  app.get("/api/creator-runs/:id/events", (request, response) => {
    const run = creatorResearchService.get(request.params.id);
    if (!run) return response.status(404).json({ error: "博主分析任务不存在" });
    const after = Math.max(0, Number(request.query.after ?? 0));
    return response.json({ events: creatorResearchService.events(run.id, Number.isFinite(after) ? after : 0) });
  });

  app.get("/api/creator-runs/:id/events/stream", (request, response) => {
    const run = creatorResearchService.get(request.params.id);
    if (!run) return response.status(404).json({ error: "博主分析任务不存在" });
    response.setHeader("Content-Type", "text/event-stream");
    response.setHeader("Cache-Control", "no-cache, no-transform");
    response.setHeader("Connection", "keep-alive");
    response.flushHeaders();
    const existing = creatorResearchService.events(run.id, 0);
    let cursor = request.query.after === undefined
      ? existing.at(-1)?.sequence ?? 0
      : Math.max(0, Number(request.query.after));
    if (!Number.isFinite(cursor)) cursor = 0;
    const emit = () => {
      for (const event of creatorResearchService.events(run.id, cursor)) {
        cursor = event.sequence;
        response.write(`id: ${event.sequence}\n`);
        response.write("event: creator-research-event\n");
        response.write(`data: ${JSON.stringify(event)}\n\n`);
      }
      response.write(": keepalive\n\n");
    };
    emit();
    const timer = setInterval(emit, 1_500);
    request.once("close", () => clearInterval(timer));
    return undefined;
  });

  app.get("/api/creator-runs/:id/portfolio", (request, response) => {
    const portfolio = creatorResearchService.portfolio(request.params.id);
    if (!portfolio) return response.status(404).json({ error: "博主分析任务不存在" });
    return response.json(portfolio);
  });

  app.post("/api/creator-runs", (request, response) => {
    try {
      const input = createCreatorResearchRunInputSchema.parse(request.body);
      return response.status(202).json(creatorResearchService.create(input.profileUrl));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "输入无效"
        : error instanceof Error ? error.message : "无法创建博主分析";
      return response.status(400).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/resume", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.resume(request.params.id));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法恢复博主分析";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  const listComparisons: express.RequestHandler = (request, response) => {
    const limit = Math.min(100, Math.max(1, Number(request.query.limit ?? 50)));
    response.json({ projects: comparisonProjectService.list(limit) });
  };

  const getComparison: express.RequestHandler = (request, response) => {
    const rawId = request.params.id;
    const id = Array.isArray(rawId) ? rawId[0] : rawId;
    if (!id) return response.status(400).json({ error: "多博主比较项目 ID 无效" });
    const project = comparisonProjectService.get(id);
    if (!project) return response.status(404).json({ error: "多博主比较项目不存在" });
    return response.json(project);
  };

  const createComparison: express.RequestHandler = (request, response) => {
    try {
      return response.status(202).json(comparisonProjectService.create(request.body));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "输入无效"
        : error instanceof Error ? error.message : "无法创建多博主比较";
      return response.status(400).json({ error: message });
    }
  };

  app.get("/api/comparison-projects", listComparisons);
  app.get("/api/comparison-projects/:id", getComparison);
  app.post("/api/comparison-projects", createComparison);
  app.get("/api/v1/comparisons", listComparisons);
  app.get("/api/v1/comparisons/:id", getComparison);
  app.get("/api/v1/comparisons/:id/dossier", (request, response) => {
    const dossier = loadComparisonDossier(comparisonProjectService, creatorResearchService, request.params.id);
    if (!dossier) return response.status(404).json({ error: "多博主研究项目不存在" });
    return response.json(dossier);
  });
  app.post("/api/v1/comparisons", createComparison);

  app.get("/api/v1/creators/:id", (request, response) => {
    const dossier = loadCreatorDossier(creatorResearchService, request.params.id);
    if (!dossier) return response.status(404).json({ error: "博主研究档案不存在" });
    return response.json(dossier);
  });

  app.get("/api/v1/creators/:id/depth-parity", (request, response) => {
    if (!["ai-red-witch", "zhang-zala", "human-director"].includes(request.params.id)) {
      return response.status(404).json({ error: "该博主尚未登记深度迁移合同" });
    }
    try {
      return response.json(buildCreatorDepthParityManifest(request.params.id as "ai-red-witch" | "zhang-zala" | "human-director"));
    } catch (error) {
      return response.status(500).json({ error: error instanceof Error ? error.message : "深度迁移清单生成失败" });
    }
  });

  app.get("/api/v1/creators/:id/videos/:videoId", (request, response) => {
    const requestedRunId = typeof request.query.run === "string" ? request.query.run : undefined;
    const evidence = loadVideoResearch(creatorResearchService, request.params.id, request.params.videoId, requestedRunId);
    if (!evidence) return response.status(404).json({ error: "视频研究证据不存在" });
    return response.json(evidence);
  });

  app.get("/api/v1/research-concepts", (_request, response) => {
    return response.json({ concepts: researchLearningService.list() });
  });

  app.get("/api/v1/research-concepts/:id", (request, response) => {
    const concept = researchLearningService.get(request.params.id);
    if (!concept) return response.status(404).json({ error: "研究概念不存在" });
    return response.json(concept);
  });

  app.get("/api/v1/learning-loops", (request, response) => {
    const rawLimit = Number(request.query.limit ?? 50);
    const limit = Number.isFinite(rawLimit) ? Math.min(100, Math.max(1, Math.trunc(rawLimit))) : 50;
    return response.json({ runs: learningLoopControlPlane.list(limit) });
  });

  app.get("/api/v1/learning-loops/:id", (request, response) => {
    const run = learningLoopControlPlane.get(request.params.id);
    if (!run) return response.status(404).json({ error: "学习循环不存在" });
    return response.json(run);
  });

  app.get("/api/v1/learning-loops/:id/events", (request, response) => {
    if (!learningLoopControlPlane.get(request.params.id)) return response.status(404).json({ error: "学习循环不存在" });
    return response.json({ events: learningLoopControlPlane.events(request.params.id) });
  });

  app.get("/api/v1/learning-loops/:id/gates", (request, response) => {
    const run = learningLoopControlPlane.get(request.params.id);
    if (!run) return response.status(404).json({ error: "学习循环不存在" });
    return response.json({ gates: run.gates });
  });

  app.get("/api/v1/learning-loops/:id/lineage", (request, response) => {
    const lineage = learningLoopControlPlane.lineage(request.params.id);
    if (!lineage) return response.status(404).json({ error: "学习循环不存在" });
    return response.json(lineage);
  });

  const learningLoopMutation = <T,>(schema: z.ZodType<T>, action: (input: T) => unknown): express.RequestHandler =>
    (request, response) => {
      try {
        return response.status(202).json(action(schema.parse(request.body)));
      } catch (error) {
        const message = error instanceof z.ZodError
          ? error.issues[0]?.message ?? "输入无效"
          : error instanceof Error ? error.message : "学习循环操作失败";
        const status = message.includes("not found") || message.includes("不存在") ? 404 : message.includes("cannot") || message.includes("required") || message.includes("missing") ? 409 : 400;
        return response.status(status).json({ error: message });
      }
    };

  app.post("/api/v1/learning-loops", learningLoopMutation(createLearningLoopInputSchema,
    (input) => learningLoopControlPlane.service.create(input)));

  // These handlers intentionally expose only bounded orchestration commands. The Dashboard remains read-only.
  app.post("/api/v1/learning-loops/:id/artifacts", (request, response) => {
    try {
      const input = addLearningLoopArtifactInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.addArtifact(request.params.id, input.operationKey, input.artifact));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/cases", (request, response) => {
    try {
      const input = addLearningLoopCasesInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.addCases(request.params.id, input.operationKey, input.cases));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/move", (request, response) => {
    try {
      const input = moveLearningLoopInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.move(request.params.id, input.operationKey, input.target));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/blind-traces", (request, response) => {
    try {
      const input = beginLearningLoopBlindInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.beginBlindTesting(request.params.id, input.operationKey, input.traces));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/lens-gates", (request, response) => {
    try {
      const input = recordLearningLoopLensGateInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.recordLensGate(request.params.id, input.operationKey, input.gate));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/blind-results", (request, response) => {
    try {
      const input = recordLearningLoopBlindResultInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.recordBlindResults(request.params.id, input.operationKey, input.updates));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/stop", (request, response) => {
    try {
      const input = stopLearningLoopInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.stop(request.params.id, input.operationKey, input.status, input.reason));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/diagnoses", (request, response) => {
    try {
      const input = recordLearningLoopDiagnosisInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.recordDiagnosis(request.params.id, input.operationKey, input.diagnosis));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/regression/begin", (request, response) => {
    try {
      const input = beginLearningLoopRegressionInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.beginRegression(request.params.id, input.operationKey));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/regressions", (request, response) => {
    try {
      const input = recordLearningLoopRegressionInputSchema.parse(request.body);
      return response.status(202).json(learningLoopControlPlane.service.recordRegression(request.params.id, input.operationKey, input.regression, input.gates));
    } catch (error) { return learningLoopError(response, error); }
  });
  app.post("/api/v1/learning-loops/:id/adjudications", (request, response) => {
    try {
      const input = adjudicateLearningLoopInputSchema.parse(request.body);
      const decisions = input.decisions.map((decision) => ({ ...decision, eligible: decision.decision === "promote" }));
      return response.status(202).json(learningLoopControlPlane.service.adjudicate(request.params.id, input.operationKey, decisions));
    } catch (error) { return learningLoopError(response, error); }
  });

  app.get("/api/runs", (request, response) => {
    const limit = Math.min(200, Math.max(1, Number(request.query.limit ?? 100)));
    response.json({ runs: service.list(limit) });
  });

  app.get("/api/runs/:id", (request, response) => {
    const report = service.get(request.params.id);
    if (!report) return response.status(404).json({ error: "分析任务不存在" });
    return response.json(report);
  });

  app.post("/api/runs", (request, response) => {
    try {
      const input = createRunInputSchema.parse(request.body);
      const report = service.create(input.url);
      response.status(202).json(report);
      void service.run(report.id, input.localVideoPath);
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "输入无效"
        : error instanceof Error ? error.message : "无法创建分析";
      response.status(400).json({ error: message });
    }
  });

  app.post("/api/runs/:id/retry", (request, response) => {
    const report = service.get(request.params.id);
    if (!report) return response.status(404).json({ error: "分析任务不存在" });
    if (report.status === "running") return response.status(409).json({ error: "任务仍在运行" });
    response.status(202).json(report);
    void service.run(report.id, typeof request.body?.localVideoPath === "string" ? request.body.localVideoPath : undefined);
    return undefined;
  });

  if (fs.existsSync(path.join(clientDirectory, "index.html"))) {
    app.use(express.static(clientDirectory, {
      setHeaders: (response, filePath) => {
        // SPA entry must never be cached — stale bundles show outdated pages.
        if (filePath.endsWith("index.html")) response.setHeader("Cache-Control", "no-cache");
      }
    }));
    app.use((request, response, next) => {
      if (request.method === "GET" && !request.path.startsWith("/api") && !request.path.startsWith("/artifacts")) {
        response.setHeader("Cache-Control", "no-cache");
        return response.sendFile(path.join(clientDirectory, "index.html"));
      }
      return next();
    });
  }

  app.use((error: unknown, _request: express.Request, response: express.Response, _next: express.NextFunction) => {
    void _next;
    const message = error instanceof Error ? error.message : "服务异常";
    response.status(500).json({ error: message });
  });
  return app;
}
