const aiRedWitch6801ThreeLens = {
  videoId: "6801c0750000000007037156",
  directing: {
    activatedQuestion: "为什么把 DeepSeek 的回答复制到文字处理文档后会出现肉眼可见的格式崩坏，以及能否用一段提示词免去手工排版？",
    promise: "视频在 0–8.92 秒先展示失败状态，并承诺用一个“神技”解决；12.75 秒后把承诺具体化为 HTML 输出与字体、字号、段落参数。",
    payoff: "25.5–27.3 秒给出层级标题和正文格式已恢复的 WPS 结果画面；它证明的是一个可见的结果状态，不证明所有中间操作或跨环境普适性。",
    endingResolution: "结尾回到同一讲解者和布景，把开场的效率承诺收束为“不用痛苦排版”的行动号召；方法层面的承诺被可见结果回应，但复制、运行 HTML、粘贴选项等执行桥接仍未解决。",
    stages: [
      {
        label: "用失败结果激活损失感",
        start: 0,
        end: 8.93,
        viewerQuestion: "我遇到的排版混乱是不是她展示的这种问题？",
        function: "先用人物口播提出效率承诺，再把抽象的兼容问题切成 WPS 文档中可见的 Markdown 残留，使观众先确认损失、后等待方法。",
        cognitiveChange: "从“可能有排版问题”转为能辨认 ####、**、连字符等具体失败签名，并形成继续观看的解决欲望。",
        proofDesign: "可见坏排版是画面证据；“复制后必然如此”和“一个神技即可解决”仍是作者主张，视频没有展示制造该失败状态的复制动作。",
        comprehensionLoad: "负荷较低：人物镜头、烧录字幕与坏排版画面重复同一痛点；但作者称其为“乱码”，容易把格式标记残留误解成字符编码故障。",
        payoff: "延迟；此段只兑现了问题可见化，没有给出方法或结果。",
        evidenceRefs: ["CUE-001", "CUE-002", "TARGET-0058", "TARGET-0003", "TARGET-0004", "SHOT-001", "SHOT-002", "SHOT-003"],
      },
      {
        label: "恢复目标内容并引出解决入口",
        start: 8.93,
        end: 12.75,
        viewerQuestion: "既然回答内容本身是想要的，究竟要改内容还是改输出形式？",
        function: "切回 DeepSeek 中《黑神话：悟空》的分节回答，明确保留内容、只改变输出与排版的任务边界。",
        cognitiveChange: "从“重新整理整篇内容”转为“原回答可保留，问题在输出/转移形式”。",
        proofDesign: "聊天界面与分节回答是可见输入状态；提供字幕中的 dipsick/dipstick 与烧录字幕、界面的 DeepSeek 读法冲突，语义只能由画面交叉支持。",
        comprehensionLoad: "负荷中等：短时间内同时出现产品名冲突、长篇回答和画中画讲解者；烧录字幕承担主要口播强化。",
        payoff: "建立方法的输入对象，但尚未给出完整提示词。",
        evidenceRefs: ["CUE-003", "TARGET-0012", "TARGET-0013", "TARGET-0087", "OCR-00152", "OCR-00804", "SHOT-004"],
      },
      {
        label: "把技巧具体化为可抄参数",
        start: 12.75,
        end: 18.57,
        viewerQuestion: "要给 DeepSeek 什么指令，才能得到目标排版？",
        function: "让观众在输入框中看到 HTML 输出、一级/二级标题、正文的字体字号与段落参数，把“神技”从口号变成可复述的提示词。",
        cognitiveChange: "从知道“用 AI 改格式”转为能说出 HTML 输出和三层排版约束。",
        proofDesign: "提示词全文由多帧输入框和 OCR 交叉支持；它证明作者输入了这些约束，不证明模型一定按所有参数渲染。",
        comprehensionLoad: "全片信息密度最高：约六秒承载 HTML、字体、字号、行距、段后距、对齐和缩进；画面保留长提示词供暂停读取，但口播只概括字体与字号。",
        payoff: "核心知识回报在此提前交付；观众已经可以抄走方法，但尚未看到输出和迁移结果。",
        evidenceRefs: ["CUE-004", "TARGET-0023", "TARGET-0025", "OCR-00360", "OCR-00361", "OCR-00362", "OCR-00363"],
      },
      {
        label: "用代码回复证明模型响应",
        start: 18.57,
        end: 21.75,
        viewerQuestion: "发出提示词后，模型究竟返回什么？",
        function: "紧接“点击发送、等它写完”的口播展示 HTML/CSS 代码块与“运行 HTML”控件，把指令与可见输出相邻放置。",
        cognitiveChange: "从抽象相信模型会处理排版，转为看到包含 html/head/style/body、h1/h2/p 的代码型回复。",
        proofDesign: "代码块是可见中间结果；由于发送点击、生成过程与运行点击均未连续展示，也没有独立 UI 声音，邻接剪辑不能升级为完整因果证明。",
        comprehensionLoad: "代码只用于充当“模型已响应”的视觉证明，观众不需要逐行理解；但“代码”与“可复制的渲染文字”之间的转换被压缩。",
        payoff: "兑现“模型能给出 HTML 输出”的局部承诺，完整文档结果继续延迟。",
        evidenceRefs: ["CUE-005", "TARGET-0029", "TARGET-0033", "SHOT-004", "SRC-AUDIO-INSPECTION"],
      },
      {
        label: "以迁移蒙太奇压缩必要操作",
        start: 21.75,
        end: 26.25,
        viewerQuestion: "怎样把代码型回复变成文字处理文档中的排版结果？",
        function: "依次给出 WPS 空白文档、运行 HTML 后的白色预览、文本选择和 WPS 右键菜单，用状态邻接暗示内容迁移。",
        cognitiveChange: "从“得到代码”转为理解需要取得渲染后的可复制文字并转入 WPS，但不能据此复述所有点击步骤。",
        proofDesign: "前后状态和选择/菜单可见；空白文档反而在选择源文本之前出现，证明这是编辑后的说明顺序。复制命令、运行点击、文件创建/保存、粘贴选项与全部切换未被建立。",
        comprehensionLoad: "表面节奏快、负荷低，实质复现负荷高：多个依赖被一组短状态镜头压缩，口播“建一个文本文档”与可见 WPS 状态也存在指代不清。",
        payoff: "提供工作流方向而非无缺口教程；结果即将出现。",
        evidenceRefs: ["CUE-005", "CUE-006", "TARGET-0036", "TARGET-0039", "TARGET-0042", "TARGET-0045", "TARGET-0096", "TARGET-0098", "SRC-AUDIO-INSPECTION"],
      },
      {
        label: "用前后对照交付结果",
        start: 26.25,
        end: 27.53,
        viewerQuestion: "最终文档是否真的比开场整齐？",
        function: "展示居中主标题、编号分节、分级小标题与正文段落，将开场的 Markdown 残留与成功状态形成视觉对照。",
        cognitiveChange: "从等待效果转为确认视频中的 WPS 最终状态已恢复层级化排版，同时保留“是否逐字同一、是否还有隐藏处理”的边界。",
        proofDesign: "TARGET-0050/0055 支持结果状态，TARGET-0003 支持失败状态；四个文本状态只确认同主题和相近四段结构，未做逐字 diff，不能证明完整无损转移。",
        comprehensionLoad: "负荷较低：结果页直接承担证明，无需新增概念；展示时间约一秒，细节校验需要暂停。",
        payoff: "兑现可见的前后差异，这是全片主回报。",
        evidenceRefs: ["CUE-006", "TARGET-0003", "TARGET-0050", "TARGET-0055", "SHOT-004"],
      },
      {
        label: "人物回场完成价值闭环",
        start: 27.53,
        end: 29.067,
        viewerQuestion: "这个技巧最终替我省掉什么，下一步做什么？",
        function: "回到同一抱猫人物与居家布景，用“不用痛苦排版”和“赶紧用起来”把单次结果上升为效率收益与行动号召。",
        cognitiveChange: "从理解一条工作流转为把它记成可立即尝试的省时技巧。",
        proofDesign: "开合场人物和措辞形成叙事闭环；省时幅度、适用环境与失败率没有外部或视频内验证。",
        comprehensionLoad: "无新增操作信息，通过人物、手势、字幕和结尾重音重复价值。",
        payoff: "情绪与行动回报完成，执行条件仍保持未知。",
        evidenceRefs: ["CUE-007", "TARGET-0066", "TARGET-0067", "SHOT-005", "SRC-AUDIO-INSPECTION"],
      },
    ],
    informationDesign: [
      {
        kind: "delayed",
        statement: "开场先交付失败画面与解决承诺，直到 12.75 秒才出现可抄提示词，25.5 秒后才出现完整成功结果。",
        start: 0,
        end: 27.3,
        evidenceRefs: ["CUE-001", "TARGET-0003", "TARGET-0023", "TARGET-0055"],
      },
      {
        kind: "compressed",
        statement: "发送、运行 HTML、取得渲染文本、复制、切换应用和粘贴被压缩为代码块—空白 WPS—预览选择—右键菜单—结果的状态蒙太奇。",
        start: 18.57,
        end: 27.3,
        evidenceRefs: ["TARGET-0033", "TARGET-0036", "TARGET-0039", "TARGET-0042", "TARGET-0045", "TARGET-0055"],
      },
      {
        kind: "repeated",
        statement: "“效率神技/解决乱码”在开场激活，“不用痛苦排版/赶紧用起来”在结尾复述并强化同一价值。",
        start: 0,
        end: 29.067,
        evidenceRefs: ["CUE-001", "CUE-002", "CUE-007", "TARGET-0058", "TARGET-0066"],
      },
      {
        kind: "withheld",
        statement: "视频未提供账号与模型版本、WPS 版本、文件格式、粘贴选项、隐私边界、失败条件和跨环境适用性；这些不是可由剪辑补齐的默认前提。",
        start: 0,
        end: 29.067,
        evidenceRefs: ["SRC-TARGETED", "CUE-001", "CUE-007"],
      },
    ],
    conflicts: [
      "提供字幕写作 dipsick/dipstick；烧录字幕、DeepSeek UI 与 OCR 支持 DeepSeek。该修复只用于语义解释，不改写逐字字幕。",
      "口播把目标应用泛称为 Word；TARGET-0036 与 TARGET-0055 可见 WPS AI/同类 WPS 文字处理界面，不能据口播认定 Microsoft Word。",
      "作者称问题是“乱码”；画面实际支持的是 ####、**、连字符等 Markdown 风格残留和层级未转换，技术成因没有被验证。",
      "旧内容架构把迁移写成连续可执行工作流；逐帧证据显示空白文档先于源文本选择出现，中间桥接被剪辑省略。",
    ],
    unknowns: [
      "提示词之外是否存在不可见上下文或系统提示。",
      "发送、生成完成与“运行 HTML”点击是否按口播顺序真实执行。",
      "“文本文档”具体指纯文本文件、HTML 文件、WPS 新建文档还是口头泛称。",
      "复制命令、应用切换、粘贴选项、保存/打开及隐藏处理的完整序列。",
      "失败文档、源回答、HTML 预览和最终文档是否逐字同一、是否完整无损转移。",
      "方法在不同系统、WPS/Word 版本、模型与文档内容中的成功率和失败条件。",
    ],
    gate: {
      ready: true,
      failedGateIds: [],
    },
  },
  visual: {
    analyzedDuration: 29.067,
    claims: [
      {
        statement: "开场和结尾使用同一外观的女性、猫与居家桌面布景，屏幕演示中保留圆形人物画中画，人物不是装饰贴片，而是贯穿教程的讲解与连续性锚点。",
        function: "用人脸、手势和生活化布景建立作者在场感，并把长达约 25 秒的屏幕录制包在同一人物叙事中。",
        start: 0,
        end: 29.067,
        evidenceRefs: ["TARGET-0058", "TARGET-0063", "TARGET-0067", "SHOT-001", "SHOT-005"],
      },
      {
        statement: "开场 WPS 文档直接显示 ####、** 和连字符条目等未转换标记，视觉上把“排版崩溃”落实为可检查的失败签名。",
        function: "problem_proof",
        start: 2.5,
        end: 5.5,
        evidenceRefs: ["TARGET-0003", "TARGET-0004", "SHOT-002"],
      },
      {
        statement: "DeepSeek 回答、提示词输入框和持续的烧录字幕共同承担高密度知识载体；提示词画面允许观众暂停读取口播未逐项念出的排版参数。",
        function: "instruction_and_parameter_proof",
        start: 8.93,
        end: 18.57,
        evidenceRefs: ["TARGET-0012", "TARGET-0023", "TARGET-0025", "OCR-00361", "OCR-00362", "OCR-00363", "CUE-004"],
      },
      {
        statement: "HTML/CSS 代码块与“运行 HTML”控件证明画面中存在代码型回复，但不证明按钮被点击、生成未被剪辑或代码与最终文档一一对应。",
        function: "intermediate_state_proof_with_causal_boundary",
        start: 19.3,
        end: 21.3,
        evidenceRefs: ["TARGET-0029", "TARGET-0033", "SHOT-004"],
      },
      {
        statement: "WPS 空白文档先出现，随后画面才切回白色 HTML 预览并选择文字，再到 WPS 右键菜单；这一画面顺序是压缩操作的蒙太奇，而非无剪辑录屏教程。",
        function: "edited_procedure_compression",
        start: 21.75,
        end: 25.1,
        evidenceRefs: ["TARGET-0036", "TARGET-0038", "TARGET-0039", "TARGET-0042", "TARGET-0045", "TARGET-0096", "TARGET-0098"],
      },
      {
        statement: "最终 WPS 画面可见居中主标题、编号分节、分级小标题与段落正文，不再以字面 ####、** 充当层级符号，形成可见的失败/结果对照。",
        function: "result_proof_and_before_after_payoff",
        start: 25.5,
        end: 27.3,
        evidenceRefs: ["TARGET-0003", "TARGET-0050", "TARGET-0055", "SHOT-004"],
      },
      {
        statement: "低音量配乐/氛围床贯穿口播，最后两秒的明亮 ding-like 重音与人物回场和 CTA 对齐；动作窗口没有独立证明发送、复制或粘贴的 UI 声音。",
        function: "pacing_and_closing_emphasis_without_procedural_proof",
        start: 0,
        end: 29.067,
        evidenceRefs: ["SRC-AUDIO-INSPECTION"],
      },
    ],
    shotSemantics: [
      {
        start: 0,
        end: 2.25,
        role: "人物钩子",
        carrier: "讲解者、猫、居家布景、手势、烧录字幕",
        meaningChange: "从无任务转为期待一个可立即使用的效率技巧。",
        evidenceRefs: ["CUE-001", "TARGET-0058", "TARGET-0059", "SHOT-001", "SHOT-002"],
      },
      {
        start: 2.25,
        end: 8.93,
        role: "失败状态证明",
        carrier: "WPS 文档、Markdown 残留、圆形人物画中画、烧录字幕",
        meaningChange: "抽象的排版痛点变成可见、可辨认的失败签名。",
        evidenceRefs: ["CUE-001", "CUE-002", "TARGET-0003", "TARGET-0004", "SHOT-002", "SHOT-003"],
      },
      {
        start: 8.93,
        end: 12.75,
        role: "输入对象建立",
        carrier: "DeepSeek 聊天回答、分节文本、画中画、字幕",
        meaningChange: "观众知道保留回答内容，后续处理的是输出与排版。",
        evidenceRefs: ["CUE-003", "TARGET-0012", "TARGET-0013", "SHOT-004"],
      },
      {
        start: 12.75,
        end: 18.57,
        role: "核心方法与参数交付",
        carrier: "提示词输入框、选中文本、OCR、画中画、字幕",
        meaningChange: "“用 AI 解决”被具体化为 HTML 输出与三层排版参数。",
        evidenceRefs: ["CUE-004", "TARGET-0023", "TARGET-0025", "OCR-00360", "OCR-00361", "OCR-00362", "OCR-00363"],
      },
      {
        start: 18.57,
        end: 21.75,
        role: "代码中间结果",
        carrier: "HTML/CSS 代码块、运行 HTML 控件、字幕、画中画",
        meaningChange: "观众看到模型已返回代码型内容，但执行与渲染仍是待跨越的桥。",
        evidenceRefs: ["CUE-005", "TARGET-0029", "TARGET-0033", "SHOT-004"],
      },
      {
        start: 21.75,
        end: 26.25,
        role: "迁移操作蒙太奇",
        carrier: "WPS 空白页、HTML 白色预览、蓝色文本选择、WPS 右键菜单",
        meaningChange: "多个可见状态暗示从渲染文字到 WPS 的转移方向，同时暴露未展示的复制/粘贴依赖。",
        evidenceRefs: ["CUE-005", "CUE-006", "TARGET-0036", "TARGET-0039", "TARGET-0042", "TARGET-0045", "TARGET-0096", "TARGET-0098"],
      },
      {
        start: 26.25,
        end: 27.53,
        role: "结果回报",
        carrier: "格式化 WPS 文档、层级标题、段落正文、字幕",
        meaningChange: "观众从等待方法成效转为看到一个结构化排版结果。",
        evidenceRefs: ["CUE-006", "TARGET-0050", "TARGET-0055", "SHOT-004"],
      },
      {
        start: 27.53,
        end: 29.067,
        role: "人物 CTA 收束",
        carrier: "同一讲解者、猫、布景、手势、烧录字幕、结尾重音",
        meaningChange: "方法的工具价值被重述为免除痛苦排版，并转为立即尝试的号召。",
        evidenceRefs: ["CUE-007", "TARGET-0066", "TARGET-0067", "SHOT-005", "SRC-AUDIO-INSPECTION"],
      },
    ],
    audioRole: "完整 0–29.067 秒音轨中，低音量配乐/氛围床承担连续节奏，末两秒 ding-like 重音承担 CTA 收束；未检测到可独立证明发送、运行、复制、粘贴或菜单确认的 UI 动作声（SRC-AUDIO-INSPECTION）。",
    conflicts: [
      "evidence pack 的 SHOT-001…005 是阈值生成的技术观察段，不等于五个语义场景或完整剪辑数；SHOT-004 内覆盖 DeepSeek、WPS、HTML 预览、选择和菜单等多个状态。",
      "旧报告记录 1.567、5.867、8.933、18.5、27.533 秒技术边界；语义分析另需按 9 个 meaning changes 分段，二者不能互相替代。",
      "口播/字幕把界面称为 Word，实际可见的是 WPS 风格文字处理界面；画面身份优先于口头泛称。",
      "剪辑把四个相近主题/结构的文本状态组成前后对照，但没有足够画面执行逐字同一性验证。",
    ],
    unknowns: [
      "屏幕演示内部所有隐藏跳切、叠化的准确位置与数量。",
      "画中画人物的真实身份、账号归属与素材授权。",
      "低音量配乐/氛围的精确曲目、类型、来源与权属。",
      "是否存在被人声完全掩蔽、机器听检未识别的极弱 UI 声音。",
      "最终 WPS 结果与源回答、HTML 预览之间的字符级同一性。",
    ],
    gate: {
      ready: true,
      failedGateIds: [],
    },
  },
} as const;

export { aiRedWitch6801ThreeLens };
export default aiRedWitch6801ThreeLens;
