const humanDirector6a2fThreeLens = {
  videoId: "6a2fcd940000000007021a9f",
  directing: {
    activatedQuestion:
      "一个没有既有粉丝的普通人，起小红书账号时究竟应先拍内容，还是先完成定位、人设、赛道与用户判断？",
    promise:
      "作者先用个人资历和一条视频起号的结果建立讲授资格，随后承诺讲清起号第一步，并把它展开为人设/定位、赛道、用户与用户需求。",
    payoff:
      "视频交付了从“我是谁”到“服务谁”的概念链、IP自我剖析问题、六类用户需求，以及更新、养号、投流和广告位边界；但没有把这些判断落成一个完整账号案例、可执行表格或发布后结果。",
    endingResolution:
      "部分兑现。定位—赛道—用户—需求的认知框架被讲完，但开场的“教会起号第一步”没有以一次实际定位产出或起号结果闭环；Vlog起号被留到下一期，结尾直接签名告别。",
    stages: [
      {
        label: "业绩拼贴先建立资格",
        start: 0.03,
        end: 2.411,
        viewerQuestion: "凭什么听这个人讲起号？",
        function: "在正文前用多个账号/作品表现截图制造高结果感，快速完成权威预热。",
        cognitiveChange: "观众从尚未判断作者可信度，转为至少知道作者声称拥有高收入编导经验和起号结果。",
        proofDesign: "视觉拼贴承担结果证明的外观，口播承担身份主张；视频没有给出截图归属、时间、平台口径或排名来源，因此只能记为作者主张与可见截图。",
        comprehensionLoad: "低：一个身份主张配一组大数字，几乎无需推理。",
        payoff: "完成注意力和资格预热，但证据边界弱。",
        evidenceRefs: ["CUE-001", "SHOT-001", "SHOT-002", "TARGET-0001"],
      },
      {
        label: "宣布第一步与人设赛道",
        start: 2.411,
        end: 13.61,
        viewerQuestion: "今天到底能学到哪一步？",
        function: "把结果承诺压缩成“起号第一步”，再用“人设与赛道”定下本期学习范围。",
        cognitiveChange: "观众从泛泛期待起号方法，变成等待一套人设与赛道选择框架。",
        proofDesign: "以口播承诺和持续烧录字幕标记范围；SRT中的“报销第一步”等明显错词需由后文语义校正，不能按字面采信。",
        comprehensionLoad: "中：开场错识别字幕和口播转折使承诺边界略显含混。",
        payoff: "明确议题，但没有先给全片路线图。",
        evidenceRefs: ["CUE-002", "CUE-003", "CUE-004", "SHOT-003", "SHOT-004", "SHOT-005"],
      },
      {
        label: "用“他媒体”重置创作出发点",
        start: 13.62,
        end: 24.24,
        viewerQuestion: "我想做什么，为什么还不是选题起点？",
        function: "用反常识短句制造第一次认知翻转，再给出资源、用户需求与平台喜好的三变量框架。",
        cognitiveChange: "观众从“做自己喜欢的东西”转向“像做产品一样，从用户、资源和平台交集决定内容”。",
        proofDesign: "主要依赖强断言、产品类比、白板指示与黄色关键词字幕，没有案例对照。",
        comprehensionLoad: "低到中：观点尖锐但框架只有三个变量，白板和手势帮助定位。",
        payoff: "交付全片的母命题，并为后续用户分析建立必要性。",
        evidenceRefs: ["CUE-005", "CUE-006", "CUE-007", "CUE-008", "CUE-009", "SHOT-006"],
      },
      {
        label: "平台机会为方法加时效性",
        start: 24.24,
        end: 36.56,
        viewerQuestion: "为什么用小红书讲，而不是任何平台都一样？",
        function: "用创作者大会经历和“80%流量给新人”说法，把定位方法绑定到素人起号机会。",
        cognitiveChange: "观众从抽象理解用户导向，转为认为小红书可能是新人实践该方法的优先场域。",
        proofDesign: "作者提供亲历来源，但未展示会议原文、适用条件或政策页面；证明强度停留在转述。",
        comprehensionLoad: "低：平台判断以单一数字和亲历叙述呈现。",
        payoff: "回答了平台选择动机，但没有完成外部验证。",
        evidenceRefs: ["CUE-010", "CUE-011", "CUE-012", "CUE-013", "SHOT-007"],
      },
      {
        label: "第一步：先定位，再用IP问题剖析自己",
        start: 36.57,
        end: 72.13,
        viewerQuestion: "起号前的定位具体要思考什么？",
        function: "先阻止观众直接拍发，再以“我是谁”为总问题，用价值排序、经历、优缺点、爱好与支出等自我问题把定位具体化。",
        cognitiveChange: "观众从把定位理解成标签，转向把它理解成一组能暴露价值观、经历、能力与生活选择的自我材料。",
        proofDesign: "口播列举问题，主持人持续指向写满内容的白板并以手指数数；视频未清晰恢复所谓“十问”的准确十项边界。",
        comprehensionLoad: "高：问题密集且分组边界不清，白板小字难以完整辨认。",
        payoff: "提供了可开始自我盘点的素材，但不是一张可直接填写的完整十问表。",
        evidenceRefs: ["CUE-014", "CUE-015", "CUE-016", "CUE-017", "CUE-018", "CUE-019", "CUE-020", "CUE-021", "CUE-022", "CUE-023", "CUE-024", "SHOT-007", "SHOT-008"],
      },
      {
        label: "第二步：列赛道并用Vlog制造后续钩子",
        start: 72.14,
        end: 85.781,
        viewerQuestion: "知道自己是谁后，内容形态怎么选？",
        function: "快速列举候选赛道，对Vlog单独画圈，再把Vlog起号的具体方法延迟到下一期。",
        cognitiveChange: "观众从只看自我定位，转为知道还需选择承载定位的赛道；同时形成对下一期的未完成期待。",
        proofDesign: "白板圈画和手势强化Vlog的特殊地位；候选词在SRT与画面之间存在不稳定，且没有选择评分标准。",
        comprehensionLoad: "中：列表推进快，缺少定义和比较维度。",
        payoff: "完成步骤命名并建立续集钩子，但赛道决策方法未兑现。",
        evidenceRefs: ["CUE-025", "CUE-026", "CUE-027", "CUE-028", "SHOT-009"],
      },
      {
        label: "第三、四步：由定位和赛道推导用户",
        start: 85.781,
        end: 95.778,
        viewerQuestion: "有了自己和赛道，下一步如何避免自说自话？",
        function: "把前两步合并成用户画像输入，再要求创作者代入用户。",
        cognitiveChange: "观众形成一条显式依赖链：我是谁 + 赛道 → 用户是谁 → 用户喜欢什么。",
        proofDesign: "依赖口播中的步骤编号与因果连接词，并由主持人转身指白板提示结构位置。",
        comprehensionLoad: "低：关系结构清晰，时间短。",
        payoff: "把此前分散概念组成可记忆的决策顺序。",
        evidenceRefs: ["CUE-029", "CUE-030", "CUE-031", "CUE-032", "SHOT-010"],
      },
      {
        label: "六类需求作为选题检查表",
        start: 95.778,
        end: 120.66,
        viewerQuestion: "用户喜欢的内容价值可以被分成哪些方向？",
        function: "连续枚举审美、共鸣、成长/价值、猎奇、情绪、解决问题，并给部分例子降低抽象度。",
        cognitiveChange: "观众从笼统追求“用户喜欢”，转为能用六个价值方向检查一个选题提供了什么。",
        proofDesign: "数字化列表、黄色关键词字幕、白板指示和情绪/问题类例子共同承担解释；未提供数据证明六类互斥或穷尽。",
        comprehensionLoad: "中到高：六项密集出现，但例子和字幕强调帮助编码。",
        payoff: "这是全片最接近可执行工具的部分，但缺少验证方法。",
        evidenceRefs: ["CUE-033", "CUE-034", "CUE-035", "CUE-036", "CUE-037", "CUE-038", "CUE-039", "SHOT-010"],
      },
      {
        label: "把运营误区改写为内容质量条件",
        start: 120.67,
        end: 150.095,
        viewerQuestion: "定位之后，更新、养号与投流有哪些底线？",
        function: "从规律更新转入反驳“养号/活跃”，再用“锦上添花、不是雪中送炭”定义投流边界，连续制造判断句。",
        cognitiveChange: "观众从可能迷信运营动作，转向把内容质量视为养号判断和投流效果的共同前提。",
        proofDesign: "用强断言、反例措辞和成语对照制造记忆点；月更示例前后字幕冲突，养号与投流也没有平台数据或投放对照。",
        comprehensionLoad: "中：观点清楚，但多个运营概念在约30秒内连续切换。",
        payoff: "提供可记忆的边界判断，证据仍是作者经验主张。",
        evidenceRefs: ["CUE-040", "CUE-041", "CUE-042", "CUE-043", "CUE-044", "CUE-045", "CUE-046", "CUE-047", "CUE-048", "CUE-049", "CUE-050", "SHOT-010", "SHOT-011", "SHOT-012"],
      },
      {
        label: "以广告位收束商业边界后直接告别",
        start: 150.095,
        end: 163.073,
        viewerQuestion: "不同内容形态为什么会影响商业化？本期框架最终落到哪里？",
        function: "先限定“以广告为生”的博主，再用广告位解释颜值/手势舞/擦边内容的变现局限，最后签名并预告式告别。",
        cognitiveChange: "观众意识到内容定位还会约束可植入场景和商业路径，但没有获得一套商业评估方法。",
        proofDesign: "用反问和缺少广告位的因果叙述收尾；没有商单样本、收入数据或植入画面。",
        comprehensionLoad: "中：新引入商业化维度，却没有回扣前面的完整步骤。",
        payoff: "形成一个强观点尾巴，但没有总结、行动清单或实际账号产出，开场承诺仅部分闭环。",
        evidenceRefs: ["CUE-051", "CUE-052", "CUE-053", "SHOT-013"],
      },
    ],
    informationDesign: [
      { kind: "authority_hook", statement: "先展示业绩拼贴并声称专业资历，压缩观众判断是否值得听的时间。", start: 0.03, end: 2.411, evidenceRefs: ["CUE-001", "SHOT-001", "SHOT-002"] },
      { kind: "promise", statement: "用“一条视频起号”接“教会第一步”，将结果与本期承诺直接相连。", start: 2.411, end: 13.61, evidenceRefs: ["CUE-002", "CUE-003", "CUE-004"] },
      { kind: "cognitive_reframe", statement: "“自媒体其实是他媒体”是全片的反常识母命题。", start: 13.62, end: 24.24, evidenceRefs: ["CUE-005", "CUE-006", "CUE-007", "CUE-008", "CUE-009"] },
      { kind: "borrowed_authority", statement: "以创作者大会亲历和80%说法为小红书选择增加时效性，但没有展示原始政策。", start: 24.24, end: 36.56, evidenceRefs: ["CUE-010", "CUE-011", "CUE-012", "CUE-013"] },
      { kind: "question_inventory", statement: "用高密度自我问题把抽象IP定位变成可被盘点的个人素材。", start: 42.23, end: 72.13, evidenceRefs: ["CUE-016", "CUE-017", "CUE-018", "CUE-019", "CUE-020", "CUE-021", "CUE-022", "CUE-023", "CUE-024"] },
      { kind: "open_loop", statement: "圈出Vlog后明确留到下一期，牺牲本期赛道决策完整度来制造续看理由。", start: 72.14, end: 85.781, evidenceRefs: ["CUE-025", "CUE-026", "CUE-027", "CUE-028", "SHOT-009"] },
      { kind: "dependency_chain", statement: "把“我是谁、选赛道、分析用户、代入用户”组织为顺序依赖，而不是四个孤立建议。", start: 85.781, end: 95.778, evidenceRefs: ["CUE-029", "CUE-030", "CUE-031", "CUE-032"] },
      { kind: "enumeration", statement: "六类需求使用编号、关键词字幕和例子，构成可记忆的选题价值清单。", start: 95.778, end: 120.66, evidenceRefs: ["CUE-033", "CUE-034", "CUE-035", "CUE-036", "CUE-037", "CUE-038", "CUE-039"] },
      { kind: "counterbelief", statement: "以强断言否定养号迷信，并用“锦上添花/雪中送炭”建立投流边界。", start: 137.44, end: 150.095, evidenceRefs: ["CUE-046", "CUE-047", "CUE-048", "CUE-049", "CUE-050"] },
      { kind: "commercial_reframe", statement: "结尾突然把内容形态重框为广告位供给问题，扩展到商业化但未完整展开。", start: 150.095, end: 163.073, evidenceRefs: ["CUE-051", "CUE-052", "CUE-053"] },
    ],
    conflicts: [
      "SRT在2.411—13.61秒出现“报销第一步”“退到铁板”等明显错识别，第一步的语义只能由后续“人设与赛道”及全片结构校正。",
      "44.402—64.19秒被作者称为“IP十问”，但口播中的项目与层级无法稳定还原为恰好十个互斥问题。",
      "123.409—137.43秒关于月更博主一个月不更新是否算断更出现相邻语句冲突，不能提炼成精确规则。",
      "开场承诺“教会起号第一步”，结尾却没有演示定位产物、发布动作或账号结果；内容框架与结果证明之间存在兑现缺口。",
    ],
    unknowns: [
      "业绩拼贴的账号归属、时间、平台口径，以及“国内收入前三”的统计范围均未知。",
      "小红书“80%流量给新人”的会议原话、有效期与适用条件未知。",
      "赛道列表的准确全集、定义和选择评分标准未知。",
      "六类用户需求是否互斥、穷尽，以及如何用用户研究验证未知。",
      "养号与投流主张的适用平台、账号阶段、预算和对照结果未知。",
    ],
    gate: { ready: true, failedGateIds: [] },
  },
  visual: {
    analyzedDuration: 163.097,
    claims: [
      { statement: "视频采用9:16竖屏，主体是戴红色蜘蛛侠风格面罩的主持人，几乎全程位于同一白板与家居/洗衣机布景前。", function: "以强识别面罩形成稳定人物锚点，以白板持续声明这是解释型内容。", start: 0.03, end: 163.073, evidenceRefs: ["SHOT-004", "SHOT-006", "SHOT-007", "SHOT-010", "SHOT-013"] },
      { statement: "0—3.733秒的多个技术镜头对应业绩截图、评论/帖子截图与人物画面快速切换，之后才进入稳定讲解布景。", function: "开头提高视觉事件密度并先呈现结果证据外观，和正文的固定机位形成节奏反差。", start: 0, end: 3.733, evidenceRefs: ["SHOT-001", "SHOT-002", "SHOT-003"] },
      { statement: "正文以中景主持人为基础，主持人反复转身、侧身指白板，白板承担步骤位置和列表关系的空间索引。", function: "在连续口播中给观众一个“现在讲到白板哪一块”的外部记忆。", start: 9.6, end: 158.31, evidenceRefs: ["SHOT-006", "SHOT-007", "SHOT-008", "SHOT-009", "SHOT-010", "SHOT-011", "SHOT-012", "SHOT-013"] },
      { statement: "主持人多次靠近镜头、举手指数、举马克笔与持纸盒/纸张，动作集中在段落切换或枚举处。", function: "用身体靠近和手势制造局部强调，弥补固定布景的视觉单调。", start: 9.6, end: 149.133, evidenceRefs: ["SHOT-005", "SHOT-006", "SHOT-008", "SHOT-010", "SHOT-011", "SHOT-012"] },
      { statement: "底部烧录字幕贯穿口播，部分关键词以黄色突出；它与白板形成“可读主句 + 空间结构”的双层信息。", function: "字幕保证高语速口播的句级可读性，黄色词承担扫描式重音。", start: 3.733, end: 163.073, evidenceRefs: ["TARGET-0005", "TARGET-0017", "TARGET-0033", "TARGET-0049", "TARGET-0053"] },
      { statement: "检测得到13个技术shot，但9.6秒后布景、人物、服装和白板连续，不能把每次技术切分解释为语义场景更换。", function: "区分运动/遮挡触发的镜头边界与真正的信息段，避免夸大剪辑复杂度。", start: 9.6, end: 163.097, evidenceRefs: ["SHOT-006", "SHOT-007", "SHOT-008", "SHOT-009", "SHOT-010", "SHOT-011", "SHOT-012", "SHOT-013"] },
      { statement: "赛道段对白板上的Vlog位置进行圈画/指示，形成全片少数可见的即时标记动作。", function: "把Vlog从口播列表中视觉抬高，并为下一期预告建立可记忆对象。", start: 72.14, end: 85.781, evidenceRefs: ["CUE-025", "CUE-026", "SHOT-009", "TARGET-0026"] },
      { statement: "结尾仍停留在同一布景，只以近身手势、签名口播和告别结束，没有结果卡、步骤总结卡或行动CTA画面。", function: "保持人格化告别，但未用视觉回顾帮助观众压缩全片框架。", start: 158.31, end: 163.073, evidenceRefs: ["CUE-053", "SHOT-013", "TARGET-0053"] },
    ],
    shotSemantics: [
      { start: 0, end: 1.033, role: "result_hook", carrier: "业绩数字与人物拼贴", meaningChange: "从无上下文直接进入高结果感，建立“此人有成绩”的第一印象；归属与口径未建立。", evidenceRefs: ["CUE-001", "SHOT-001"] },
      { start: 1.033, end: 3.733, role: "authority_context", carrier: "评论/帖子类截图、人物近景与口播字幕", meaningChange: "将抽象资历主张连接到社交平台内容外观，再转入作者本人。", evidenceRefs: ["CUE-001", "CUE-002", "SHOT-002", "SHOT-003"] },
      { start: 3.733, end: 13.61, role: "promise_setup", carrier: "主持人中近景、面罩、烧录字幕、手势", meaningChange: "由结果展示切入教学承诺，界定本期为人设与赛道。", evidenceRefs: ["CUE-002", "CUE-003", "CUE-004", "SHOT-004", "SHOT-005", "SHOT-006"] },
      { start: 13.62, end: 36.56, role: "thesis_and_context", carrier: "主持人口播、白板、指示手势、黄色关键词字幕", meaningChange: "先以“他媒体”翻转创作观，再用小红书新人机会说明为何此时讨论。", evidenceRefs: ["CUE-005", "CUE-008", "CUE-011", "CUE-013", "SHOT-006", "SHOT-007"] },
      { start: 36.57, end: 72.13, role: "identity_inventory", carrier: "白板长列表、主持人数数/指写、字幕", meaningChange: "把定位从口号变成围绕价值、经历、能力和生活选择的自我问题集合。", evidenceRefs: ["CUE-015", "CUE-017", "CUE-018", "CUE-022", "CUE-024", "SHOT-007", "SHOT-008"] },
      { start: 72.14, end: 85.781, role: "track_selection_open_loop", carrier: "白板赛道区、圈画Vlog、字幕", meaningChange: "从“我是谁”切到内容赛道，并将Vlog的方法延迟为续集。", evidenceRefs: ["CUE-025", "CUE-026", "CUE-027", "CUE-028", "SHOT-009"] },
      { start: 85.781, end: 120.66, role: "user_value_framework", carrier: "主持人指板、六项口播列表、黄色关键词字幕", meaningChange: "把定位和赛道连接到用户，再把用户偏好拆成六类内容价值。", evidenceRefs: ["CUE-029", "CUE-030", "CUE-032", "CUE-033", "CUE-039", "SHOT-010"] },
      { start: 120.67, end: 137.43, role: "operating_rules", carrier: "固定中景、白板、规律更新口播", meaningChange: "从选题价值切到账号运营底线，提出不断更和规律更新。", evidenceRefs: ["CUE-040", "CUE-041", "CUE-042", "CUE-045", "SHOT-010", "SHOT-011"] },
      { start: 137.44, end: 150.095, role: "myth_rebuttal", carrier: "主持人靠近/指示手势、强措辞字幕", meaningChange: "否定养号迷信，并以内容质量重设投流的作用边界。", evidenceRefs: ["CUE-046", "CUE-047", "CUE-048", "CUE-049", "CUE-050", "SHOT-012"] },
      { start: 150.095, end: 163.097, role: "commercial_tail_and_signoff", carrier: "同一白板布景、主持人口播、字幕与告别手势", meaningChange: "把内容形态重框为广告位问题后结束；没有视觉总结或结果闭环。", evidenceRefs: ["CUE-051", "CUE-052", "CUE-053", "SHOT-013"] },
    ],
    audioRole:
      "可确认AAC音轨存在，语音口播是全片的主信息载体，字幕与手势跟随其节奏；现有证据无法可靠区分或解释背景音乐、音效及其在开头切换和段落转场中的语义作用。",
    conflicts: [
      "场景检测得到13个shot，但正文布景、服装、人物与白板连续；技术切分可能来自运动或遮挡，不能等同于13个语义场景。",
      "烧录字幕可纠正部分SRT错词，但白板小字与OCR置信度不足，不能为了形成整齐列表而静默补全。",
      "开场截图视觉上像结果证据，但其账号归属、日期、平台口径与作者关系不可由画面确认。",
    ],
    unknowns: [
      "非语音音频中是否存在背景音乐、节奏点或提示音，以及它们与切镜的精确关系未知。",
      "白板全部小字、颜色编码的精确含义和所谓IP十问的完整空间分组未知。",
      "13个技术shot中哪些是实际剪辑、哪些由运动/遮挡触发检测未知。",
      "主持人真实身份、面罩角色授权和拍摄机位/焦段参数未知。",
      "视频是否使用隐蔽跳剪、变速或音频重录，现有帧级证据不足以确定。",
    ],
    gate: { ready: false, failedGateIds: ["VE-NON_SPEECH_AUDIO_UNRESOLVED", "VE-BOARD_TEXT_PARTIAL", "VE-EDIT_BOUNDARY_UNVERIFIED"] },
  },
} as const;

export default humanDirector6a2fThreeLens;
export { humanDirector6a2fThreeLens };
