const zhangZala69fe = {
  videoId: "69fe6f3a000000001a036be4",
  directing: {
    activatedQuestion:
      "同样使用 AI 制作 HTML Slides，为什么有些成品明显更好看，以及普通人怎样稳定获得这种结果？",
    promise:
      "作者先把答案归结为可复用的审美模板资产，再承诺按用户技术能力给出 AnyGen 与 GitHub/coding agent 两条使用路径。",
    payoff:
      "观众看到模板库的结果跨度、AnyGen 的选择与生成界面、GitHub 仓库及 instructions 结构，并获得两条入口各自的最小操作顺序；片内未证明端到端可复现性。",
    endingResolution:
      "结尾不以单纯下载 CTA 收束，而把 HTML Slides 上升为对外品味和 AI-native 身份信号；这一感知效果属于作者主张，并无客户反馈证据。",
    stages: [
      {
        label: "成品先行：制造审美结果差距",
        start: 0,
        end: 13.52,
        viewerQuestion: "这些 Slides 为什么看起来比普通 AI 成品更好？",
        function: "用连续成品而非抽象讲解激活欲望，再把好看/不好看的差距变成待回答问题。",
        cognitiveChange: "从‘AI 会生成 Slides’转为意识到同样使用 AI 仍存在显著审美差距。",
        proofDesign: "多套版式、图表与配色结果快速切换；口播连续提出同样使用 AI 却效果不同。",
        comprehensionLoad: "低：观众先比较结果，不需要理解工具或流程。",
        payoff: "建立明确的想要感与继续观看理由。",
        evidenceRefs: [
          "CUE-001",
          "CUE-002",
          "CUE-003",
          "CUE-004",
          "CUE-005",
          "SHOT-001",
          "SHOT-012",
          "TARGET-0001",
          "TARGET-0011",
          "OCR-00004",
        ],
      },
      {
        label: "解释机制：把个人审美固化为模板资产",
        start: 13.52,
        end: 54.76,
        viewerQuestion: "决定结果上限的究竟是什么？",
        function: "把开场的审美差距归因于 Skill、参考风格与三十多个模板，而不是一次性的提示词技巧。",
        cognitiveChange: "从寻找神奇 prompt 转向把审美参考、模板和说明理解为可积累资产。",
        proofDesign: "作者关于 Skill、模板数量和制作方式的口述，与大量不同风格模板的结果蒙太奇并置；数量、工具分工及授权没有逐项验证。",
        comprehensionLoad: "中：抽象的‘审美’被拆成参考库、Skill、模板三个较易理解的资产层。",
        payoff: "给出可复用机制，并以视觉多样性建立模板库的规模感。",
        evidenceRefs: [
          "CUE-006",
          "CUE-007",
          "CUE-008",
          "CUE-009",
          "CUE-010",
          "CUE-016",
          "SHOT-013",
          "SHOT-034",
          "TARGET-0012",
          "TARGET-0016",
          "TARGET-0033",
          "OCR-00084",
          "OCR-00144",
        ],
      },
      {
        label: "门槛分流：把一个资产拆成两条路径",
        start: 54.76,
        end: 57.4,
        viewerQuestion: "我没有 coding agent，是否仍然能使用这些模板？",
        function: "在展示价值之后才按技术门槛分流，避免小白因 GitHub/coding agent 预先流失。",
        cognitiveChange: "从担心工具门槛转为知道存在小白路径和 coding agent 路径。",
        proofDesign: "口播明确宣告‘两种方式’，画面维持结果样例，随后切入平台界面。",
        comprehensionLoad: "低：只建立二分选择，细节留到后续。",
        payoff: "小白先得到可进入性承诺，进阶用户也知道稍后还有仓库路径。",
        evidenceRefs: [
          "CUE-017",
          "SHOT-034",
          "SHOT-035",
          "SHOT-036",
          "TARGET-0033",
          "TARGET-0034",
          "OCR-00144",
          "OCR-00154",
        ],
      },
      {
        label: "小白路径：AnyGen 的界面化操作演示",
        start: 57.4,
        end: 110.93,
        viewerQuestion: "不使用 coding agent 时，我具体在哪里选模板、输入需求并拿到结果？",
        function: "用平台界面把模板资产转成低门槛动作：进入 Slides 功能、选 Frontend Slides、选模板作参考、输入需求、生成、调整和分享。",
        cognitiveChange: "从只知道有模板转为拥有一条可复述的 AnyGen 使用顺序。",
        proofDesign: "长段屏幕录制展示模板、输入框与完成态，并插入作者旧案例；剪辑没有保留提交、等待和全部修改的连续闭环。",
        comprehensionLoad: "中高：连续出现产品名、功能名、选择项和多次 UI 状态，烧录字幕承担操作提示。",
        payoff: "得到不依赖 coding agent 的最低门槛入口，以及‘模板先于提示词’的案例化说明。",
        evidenceRefs: [
          "CUE-018",
          "CUE-020",
          "CUE-021",
          "CUE-023",
          "CUE-027",
          "CUE-028",
          "CUE-030",
          "CUE-032",
          "CUE-034",
          "CUE-035",
          "CUE-036",
          "SHOT-037",
          "SHOT-038",
          "SHOT-039",
          "TARGET-0038",
          "TARGET-0044",
          "TARGET-0052",
          "TARGET-0063",
          "TARGET-0070",
          "OCR-00162",
          "OCR-00173",
          "OCR-00223",
        ],
      },
      {
        label: "进阶路径：GitHub 资产交给 coding agent",
        start: 110.93,
        end: 151.45,
        viewerQuestion: "已有 coding agent 时，仓库里究竟有什么，agent 凭什么选择模板？",
        function: "把同一套审美资产从平台功能扩展为仓库中的 HTML、预览、instructions、描述和关键词。",
        cognitiveChange: "从把模板理解为静态文件，转为理解它还包含供 agent 检索和匹配的说明层。",
        proofDesign: "GitHub 仓库、文件列表、模板预览和说明页面与口播同步出现；没有连续展示 clone、安装、agent 读取或匹配结果。",
        comprehensionLoad: "中：概念清楚，但仓库小字、英文名和被剪掉的执行环节增加复现负担。",
        payoff: "进阶用户得到第二条入口及其资产结构，而非只得到一个泛化的‘去 GitHub’指令。",
        evidenceRefs: [
          "CUE-037",
          "CUE-038",
          "CUE-039",
          "CUE-040",
          "CUE-041",
          "CUE-042",
          "CUE-043",
          "SHOT-039",
          "SHOT-040",
          "SHOT-041",
          "SHOT-042",
          "TARGET-0081",
          "TARGET-0090",
          "TARGET-0097",
          "TARGET-0109",
          "OCR-00264",
          "OCR-00276",
          "OCR-00283",
        ],
      },
      {
        label: "身份收束：从制作方式升级为 AI-native 信号",
        start: 151.45,
        end: 173.467,
        viewerQuestion: "除了好看，为什么值得改变现有 Slides 工作方式？",
        function: "再次展示高设计感成品，把功能收益升维为对外品味、专业形象和 AI-native 身份。",
        cognitiveChange: "从把 HTML Slides 当工具技巧转向把它视为对外表达方式。",
        proofDesign: "结果蒙太奇可证明画面风格多样且醒目；‘只有 HTML 能实现’及客户会形成特定判断没有比较实验或用户证据。",
        comprehensionLoad: "低：停止新增步骤，以价值判断和结果回看完成记忆收束。",
        payoff: "回应开场的审美问题，并给使用行为附加身份意义。",
        evidenceRefs: [
          "CUE-044",
          "CUE-045",
          "CUE-046",
          "CUE-047",
          "SHOT-043",
          "SHOT-054",
          "TARGET-0117",
          "TARGET-0123",
          "TARGET-0128",
          "OCR-00310",
          "OCR-00330",
          "OCR-00345",
        ],
      },
    ],
    informationDesign: [
      {
        kind: "delayed",
        statement: "先用约 55 秒建立结果欲望和模板资产价值，之后才公布两条使用路径，工具门槛不会抢走开场注意力。",
        start: 0,
        end: 57.4,
        evidenceRefs: ["CUE-001", "CUE-016", "CUE-017", "SHOT-001", "SHOT-036"],
      },
      {
        kind: "repeated",
        statement: "Slides 成品在开场、模板解释、AnyGen 案例和结尾反复出现，持续承担欲望、证明和记忆收束，而不只是装饰 B-roll。",
        start: 0,
        end: 173.467,
        evidenceRefs: ["TARGET-0001", "TARGET-0016", "TARGET-0052", "TARGET-0117", "TARGET-0128"],
      },
      {
        kind: "compressed",
        statement: "AnyGen 与 GitHub 的真实执行被压缩成若干界面状态和口播步骤；视频讲清概念顺序，但不等于无剪辑、可复现的端到端教程。",
        start: 57.4,
        end: 151.45,
        evidenceRefs: ["SHOT-037", "SHOT-039", "SHOT-040", "CUE-020", "CUE-043"],
      },
      {
        kind: "withheld",
        statement: "片内没有提供费用、地区、账户条件、仓库许可证、完整提示词、等待时长和镜头外修改，因此结果因果与复现成本保持未知；这里不推断为作者故意隐瞒。",
        start: 50.92,
        end: 151.45,
        evidenceRefs: ["CUE-016", "CUE-034", "CUE-035", "CUE-039", "SRC-TARGETED"],
      },
      {
        kind: "delayed",
        statement: "‘AI-native 身份’直到教程路径结束后才出现，把功能型收益作为可信基础，再完成价值升维。",
        start: 151.45,
        end: 173.467,
        evidenceRefs: ["CUE-044", "CUE-047", "TARGET-0117", "TARGET-0128"],
      },
    ],
    conflicts: [
      "机器转写把 PPT、Claude Code、coding agent、Build Slides 等专有名词识别成 PBT、Clocko、扣顶、Billed；本 overlay 只在烧录字幕或 UI 支持时采用规范化阅读，原始 cue 不被改写。",
      "作者称约三轮提示即可得到案例结果，但视频未展示全部提示、生成等待与镜头外修改，不能把剪辑后顺序解释为连续因果。",
      "‘只有 HTML 能实现类似效果’与‘客户会觉得你 AI-native’是作者判断；结果画面不能替代 PowerPoint 对照实验或客户反馈。",
    ],
    unknowns: [
      "三十多个模板的精确清单、图片/字体/设计参考来源和授权。",
      "AnyGen 当前版本、费用、账户、地区、配额、导出与分享限制。",
      "GitHub 仓库当前入口、版本、许可证、安装命令与 agent 支持范围。",
      "案例的完整 prompts、真实生成时长、人工修改量和同输入复现质量。",
      "独立 reviewer 尚未对该条编导 overlay 做盲评。",
    ],
    gate: {
      ready: false,
      failedGateIds: ["DL-GATE-INDEPENDENT-EVALUATION-MISSING"],
    },
  },
  visual: {
    analyzedDuration: 173.467,
    claims: [
      {
        statement: "竖屏输出画布中居中放置横向 Slides 或桌面界面，上下保留大面积黑色留白，视觉注意力集中在中部演示带。",
        function: "在小红书竖屏容器中保留 16:9 作品和桌面 UI 的完整横向构图。",
        start: 0,
        end: 173.467,
        evidenceRefs: ["TARGET-0001", "TARGET-0038", "TARGET-0081", "TARGET-0117"],
      },
      {
        statement: "主讲人的圆形真人画中画持续位于主体演示的右下角，作品/UI 占据主面积，人物不切回全屏。",
        function: "维持身份、表情与口播归属，同时不牺牲屏幕演示的信息面积。",
        start: 0,
        end: 173.467,
        evidenceRefs: ["TARGET-0001", "TARGET-0016", "TARGET-0038", "TARGET-0081", "TARGET-0117", "TARGET-0128"],
      },
      {
        statement: "中文烧录字幕稳定置于中部演示带下缘、人物画中画左侧附近，并在专有名词处提供比 ASR 更可靠的视觉锚点。",
        function: "降低静音观看成本，并把口播与当前画面状态绑定；字幕同时可能遮挡底部 UI 小字。",
        start: 0,
        end: 173.467,
        evidenceRefs: ["OCR-00004", "OCR-00144", "OCR-00162", "OCR-00264", "OCR-00310", "OCR-00345", "SRC-OCR"],
      },
      {
        statement: "0–54.76 秒以大量约 1–4 秒的模板结果切换为主，先后覆盖图表、信息卡、强字体和不同配色，而非停留在单一案例。",
        function: "用剪辑密度建立审美广度、资产规模与新鲜感，支撑‘模板库’而非‘一个模板’的认知。",
        start: 0,
        end: 54.76,
        evidenceRefs: ["SHOT-001", "SHOT-020", "SHOT-024", "SHOT-030", "SHOT-034", "TARGET-0001", "TARGET-0016"],
      },
      {
        statement: "57.5–124.367 秒主要由三个明显更长的桌面录屏镜头承载，剪辑节奏从结果蒙太奇降速，允许观众读取 AnyGen 的界面状态和案例结果。",
        function: "在欲望建立后切换到解释/操作模式，让界面本身成为知识载体。",
        start: 57.5,
        end: 124.367,
        evidenceRefs: ["SHOT-037", "SHOT-038", "SHOT-039", "TARGET-0038", "TARGET-0044", "TARGET-0052", "TARGET-0063"],
      },
      {
        statement: "110.93–150.967 秒由 GitHub 仓库、模板预览和说明相关界面接管主体画面，画面切换对应第二条技术路径。",
        function: "把口播中的‘仓库资产’具体化为文件、预览与 instructions/描述结构，但不证明 agent 已实际执行。",
        start: 110.93,
        end: 150.967,
        evidenceRefs: ["SHOT-039", "SHOT-040", "SHOT-041", "SHOT-042", "TARGET-0081", "TARGET-0090", "TARGET-0097"],
      },
      {
        statement: "151 秒后重新恢复较密集的成品切换，停止新增 UI 步骤，让视觉结果为‘品味与 AI-native’的身份主张收束。",
        function: "用结果回环回应开场，在结尾保持美感强度并完成身份化记忆。",
        start: 150.967,
        end: 173.467,
        evidenceRefs: ["SHOT-043", "SHOT-048", "SHOT-054", "TARGET-0117", "TARGET-0123", "TARGET-0128"],
      },
    ],
    shotSemantics: [
      {
        start: 0,
        end: 13.52,
        role: "result_hook",
        carrier: "高设计感 Slides 成品、烧录字幕、右下角真人画中画",
        meaningChange: "先让观众看见审美差距，再提出同样使用 AI 为什么结果不同。",
        evidenceRefs: ["CUE-001", "CUE-005", "SHOT-001", "SHOT-012", "TARGET-0001", "TARGET-0011"],
      },
      {
        start: 13.52,
        end: 54.76,
        role: "asset_scale_proof",
        carrier: "多风格模板蒙太奇与作者关于 Skill/三十多个模板的口播",
        meaningChange: "把一个漂亮结果扩展为有规模、可复用的审美资产库。",
        evidenceRefs: ["CUE-006", "CUE-016", "SHOT-013", "SHOT-034", "TARGET-0012", "TARGET-0016"],
      },
      {
        start: 54.76,
        end: 57.4,
        role: "route_transition",
        carrier: "‘两种方式’口播、结果样例与切入平台界面的转场",
        meaningChange: "从价值证明切换为按技术门槛选择入口。",
        evidenceRefs: ["CUE-017", "SHOT-034", "SHOT-036", "TARGET-0033", "TARGET-0034"],
      },
      {
        start: 57.4,
        end: 110.93,
        role: "anygen_walkthrough",
        carrier: "AnyGen 桌面界面、模板/输入/结果状态、字幕与画中画",
        meaningChange: "把抽象模板资产转成小白可复述的平台操作顺序。",
        evidenceRefs: ["CUE-020", "CUE-036", "SHOT-037", "SHOT-038", "SHOT-039", "TARGET-0038", "TARGET-0063"],
      },
      {
        start: 110.93,
        end: 151.45,
        role: "github_asset_walkthrough",
        carrier: "GitHub 仓库、文件列表、预览与 instructions 相关界面",
        meaningChange: "从平台内使用扩展到 coding agent 可读取和匹配的仓库资产。",
        evidenceRefs: ["CUE-037", "CUE-043", "SHOT-039", "SHOT-040", "SHOT-041", "SHOT-042", "TARGET-0081", "TARGET-0097"],
      },
      {
        start: 151.45,
        end: 173.467,
        role: "identity_resolution",
        carrier: "成品蒙太奇、AI-native 口播、字幕与持续画中画",
        meaningChange: "从制作技巧升维为对外品味和 AI-native 身份信号。",
        evidenceRefs: ["CUE-044", "CUE-047", "SHOT-043", "SHOT-054", "TARGET-0117", "TARGET-0128"],
      },
    ],
    audioRole:
      "完整混合轨 0–173.546 秒经无缝 10 秒窗机器检查后，Speech 在每个窗口稳定居首，因此可确认旁白持续承担主要解释；其他 vehicle、rumble 等低分标签不稳定且与画面语义不可靠，不能据此确认背景音乐、UI 点击音、生成成功音或其编辑功能。该检查不是人耳听检，也未做声源分离。证据：SRC-AUDIO。",
    conflicts: [
      "镜头切换与 UI 状态顺序可被观察，但抽帧和剪辑后的时间线不能证明操作在同一任务中连续发生。",
      "烧录字幕能校正部分专有名词，同时会遮挡演示带底部；不能把未读出的 UI 小字当作不存在。",
      "结果蒙太奇证明成品视觉多样，但不能证明每个成品均由片中展示的同一流程、同一模板库或同一次生成得到。",
    ],
    unknowns: [
      "画面中全部英文小字、字体名称、模板来源和素材授权。",
      "AnyGen 提交、等待、失败/重试、导出及外部打开的连续镜头。",
      "GitHub clone、安装、agent 调用、模板匹配与最终输出的连续屏幕证据。",
      "非旁白音频是否包含低电平音乐或 UI 声；混合轨机器分类无法确认声源、曲目或版权。",
      "独立 reviewer 尚未对镜头语义和画面功能判断做盲评。",
    ],
    gate: {
      ready: false,
      failedGateIds: [
        "VE-GATE-INDEPENDENT-EVALUATION-MISSING",
        "VE-GATE-NONSPEECH-AUDIO-NOT-SOURCE-SEPARATED",
      ],
    },
  },
} as const;

export { zhangZala69fe };
export default zhangZala69fe;
